const StudentApplication = require("../model/masters/studentApplication/studentApplication");
const Lead = require("../model/lead");
const Invoice = require("../model/generateInvoice");
const Role = require("../model/masters/roles");
const User = require("../model/user");

const { sendEmail, getConfig } = require("../middleware/nodemailer");

async function sendEODReport() {
  try {
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const end = new Date();
    end.setHours(23, 59, 59, 999);

    // --- Calculate ---
    const todayInvoices = await Invoice.aggregate([
      { $unwind: "$paidAmount" },
      {
        $match: {
          "paidAmount.date": { $gte: start, $lte: end },
          // created_by_type: "user",
        },
      },
      {
        $group: {
          _id: null,
          total: { $sum: { $toDouble: "$paidAmount.amount" } },
        },
      },
    ]);

    const totalCollection = todayInvoices[0]?.total || 0;

    const todayApplications = await StudentApplication.countDocuments({
      createdAt: { $gte: start, $lte: end },
      created_by_type: "user",
    });

    const totalLeads = await Lead.countDocuments({
      createdAt: { $gte: start, $lte: end },
      created_by_type: "user",
    });

    const totalPendingLeads = await Lead.countDocuments({
      createdAt: { $gte: start, $lte: end },
      created_by_type: "user",
      lead_status: "New",
    });

    // --- Find Super Admin Role ---
    const superAdminRole = await Role.findOne({
      name: "Super Admin",
      branchId: { $exists: false },
    });

    if (!superAdminRole) {
      console.warn("⚠️ Super Admin role not found.");
      return false;
    }

    // --- Find Super Admin Users ---
    const superAdmins = await User.find({ role: superAdminRole._id }).select(
      "email"
    );

    if (!superAdmins.length) {
      console.warn("⚠️ No Super Admin users found.");
      return false;
    }

    // --- Config Logos ---

    const baseUrl = process.env.BASE_URL || "http://69.62.75.212:3000/api/";
    const config = await getConfig();
    const topLogoUrl = config.gmail?.topLogo
      ? process.env.BASE_URL + config.gmail.topLogo
      : "";
    const bottomLogoUrl = config.gmail?.bottomLogo
      ? process.env.BASE_URL + config.gmail.bottomLogo
      : "";

    // --- HTML Template (same style as OTP) ---
    const reportHtml = `
      <div style="font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #fff; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">

          <!-- Top Logo -->
          <div style="text-align: center; padding: 20px 0; background-color: #f4f4f4; border-radius: 8px 8px 0 0;">
            <img src="${topLogoUrl}" alt="Logo" style="width: 100px; height: auto;">
          </div>

          <!-- Report Content -->
          <div style="padding: 20px; text-align: center;">
            <h2 style="color: #333;">📊 End of Day Report</h2>
            <p style="font-size: 16px; color: #666;">Here is the summary for <b>${new Date().toLocaleDateString()}</b></p>
            
            <div style="background-color: #f4f4f4; padding: 15px; border-radius: 4px; margin: 20px auto; display: inline-block; text-align: left;">
              <p><strong>Today's Collection:</strong> ₹${totalCollection.toFixed(
                2
              )}</p>
              <p><strong>Today's Applications:</strong> ${todayApplications}</p>
              <p><strong>Today's Leads:</strong> ${totalLeads}</p>
              <p><strong>Today's Pending Leads:</strong> ${totalPendingLeads}</p>
            </div>

            <p style="font-size: 14px; color: #999;">This is an automated report generated by SmartX CRM.</p>
          </div>

          <!-- Bottom Logo -->
          <div style="text-align: center; padding: 20px 0; background-color: #f4f4f4; border-radius: 0 0 8px 8px;">
            <p style="margin: 0 0 5px 0; font-size: 12px; color: #555;">Powered by</p>
            <img src="${bottomLogoUrl}" alt="Logo" style="width: 150px; height: auto;">
          </div>

        </div>
      </div>
    `;

    const subject = `EOD Report - ${new Date().toLocaleDateString()}`;

    // --- Send Emails ---
    for (const admin of superAdmins) {
      await sendEmail(admin.email, subject, reportHtml);
    }

    console.log("✅ EOD Report sent successfully to super admins.");
    return true;
  } catch (error) {
    console.error("❌ Error in sending EOD Report:", error);
    return false;
  }
}

module.exports = sendEODReport;
