module.exports = {
  Australia: [
    "offerLetter",
    "coe",
    "medicalExamination",
    "tuitionFeePayment",
    "oshc",
    "immiAccount",
    "visaApplication",
    "visaFeePayment",
    "biometrics",
    "visaOutCome",
    "travelPreparation",
  ],

  Canada: [
    "conditionalOfferLetter",
    "medicalProcess",
    "tutuionFeePayment",
    "gicDetails",
    "gckeyAccount",
    "applicationFormLock",
    "visaFeePayment",
    "submissionConfirmation",
    "biometricRequest",
    "bvlAndPpr",
    "visaDecision",
    "poeLetter",
    "permits",
  ],

  France: [
    "admissionLetter",
    "campusFranceRegistration",
    "tuitionFeePayment",
    "proofOfFunds",
    "medicalInsurance",
    "franceVisasForm",
    "visaFeePayment",
    "appointmentBooking",
    "biometricsSubmission",
    "visaDecision",
    "postArrivalFormalities",
  ],

  Germany: [
    "admissionLetter",
    "blockedAccount",
    "healthInsurance",
    "visaApplicationForm",
    "appointmentBooking",
    "visaFeePayment",
    "biometricsInterview",
    "visaDecision",
    "travelResidencePermit",
  ],

 "United Kingdom": [
    "cas",
    "tuitionAndFunds",
    "tbTest",
    "visaApplicationForm",
    "fees",
    "biometricAppointment",
    "biometricCompletion",
    "visaDecision",
  ],

 "United States": [
    "i20Application",
    "i20Received",
    "ds160Registration",
    "ds160Confirmation",
    "visaFeePayment",
    "appointmentBooking",
    "sevisPayment",
    "fundsShow",
    "visaDecision",
  ],    

  Universal: [
    "status",
    "paymentDetails",
    "feeStatus",
    "biometricsUploaded",
    "VFSAppointmentDateTime",
    "visaFileHandover",
    "d_visa_apply",
    "visaFileSubmission",
    "visaOnlineSubmission",
    "visaOutcomeStatus",
    "visaOutcomeDate",
    "RP_decisionDate",
    "remarks",
    "rejectionReason",
    "appealOption",
  ],
};
